### PR TITLE
Go step definitions support

### LINKED ISSUE #72: Add support for Go (Godog)
See [CONTRIBUTING.md](https://github.com/cucumber/language-service/blob/main/CONTRIBUTING.md) for detailed instructions about how to prepare a pull request for this.

### PR DESCRIPTION
**Pull request by mirogta**
### 🤔 What's changed?

* Added support for Go (https://github.com/cucumber/godog) - this should fix #72 

Used https://tree-sitter.github.io/tree-sitter/playground to figure out the syntax tree.

`godog` doesn't have support for Parameter Types so not using it. (The other BDD library in Go, https://github.com/go-bdd/gobdd has support for Parameter Types, but it's obsolete…)

`godog` doesn't use `Given`, `When` or `Then` keywords, but instead a generic `Step` keyword.

* You probably don't want `.vscode/launch.json` and `.vscode/settings.json` committed, but I've left it there for my own sake to be able to debug this faster. Happy to remove them for the final commit before merging.

### ⚡️ What's your motivation? 

* To make this finally usable in Go

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

Unit tests are passing… I'm new to vscode extension development, so please bear with me.
I'm trying to follow [this](https://github.com/cucumber/vscode/blob/main/CONTRIBUTING.md) and have added `go` support to both `cucumber/language-server` and `cucumber/vscode` locally, but somehow I can't get it work. Can someone please advise how do I debug that? The guide in `cucumber/vscode` says "Chose `Run -> Run without debugging`".

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by GadiZimerman** [comment]
@CodiumAI-Agent review

**Comment by GadiZimerman** [comment]
@CodiumAI-Agent /review

**Comment by cpunion** [comment]
What is the status of this PR?

**Comment by iamNoah1** [comment]
hei @mirogta wanna to check in what the progress is here and if you need some help by any chance?!

**Comment by mirogta** [comment]
@cpunion @iamNoah1 - if this looks abandoned, that's because I had other priorities. Happy for anyone else to pick this up and continue/get it done. I won't have bandwidth for it anytime soon.

**Comment by lucas-deangelis** [comment]
What are the current blockers for this PR to be merged? I'm assuming that the first two comments raised by @CodiumAI-Agent should be fixed, but the third is not specific to the integration of Go, but I'm not certain. Is there anything else needed?

**Comment by mirogta** [comment]
> What are the current blockers for this PR to be merged? I'm assuming that the first two comments raised by @CodiumAI-Agent should be fixed, but the third is not specific to the integration of Go, but I'm not certain. Is there anything else needed?

That + the two branch conflicts + running a test that this actually works

**Comment by kieran-ryan** [comment]
Sincere thanks for this contribution @mirogta! We'll roll this into a coming release. Have tested and made the following changes:

- Support for `Given`, `When` and `Then` step definition keywords - introduced through cucumber/godog#509
- Support for `interpreted_string_literal` (`"the bee's knees"`) further to `raw_string_literal` (`^a regexp$`)
- Added required `expression_statement` to the tree-sitter query
- Removed the VSCode extension settings, Go test data lock files; and commented code highlighted by @CodiumAI-Agent
- Bumped `tree-sitter-go` to v0.20.0
- Replaced Rust step definition in Go implementation with a Go sample
- Added unit test for the Go string literal function

> I'm trying to follow [this](https://github.com/cucumber/vscode/blob/main/CONTRIBUTING.md) and have added go support to both cucumber/language-server and cucumber/vscode locally, but somehow I can't get it work. Can someone please advise how do I debug that? The guide in cucumber/vscode says "Chose Run -> Run without debugging".

Have recently overhauled the [VSCode extension contributing guidelines](https://github.com/cucumber/vscode/blob/45745cfdad35cf0a1bf52af0de6563471e9ccba9/CONTRIBUTING.md), feel free to give it a go and raise a PR or issue if any improvements or feedback.

**Review by kieran-ryan — APPROVED** [review]

**Comment by aslakhellesoy** [comment]
Hi @mirogta,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
